# frozen_string_literal: true

require_relative "../../foo"

RSpec.describe Dry::CLI::Completion::Generator do
  subject do
    Dry::CLI::Completion::Generator.new(Foo::CLI::Commands).call(shell: Dry::CLI::Completion::ZSH)
  end

  it "returns completion script for zsh" do
    is_expected.to eq <<~SCRIPT
      # enable bash completion support, see https://github.com/dannyben/completely#completions-in-zsh
      autoload -Uz +X compinit && compinit
      autoload -Uz +X bashcompinit && bashcompinit
      # rspec completion                                         -*- shell-script -*-

      # This bash completions script was generated by
      # completely (https://github.com/dannyben/completely)
      # Modifying it manually is not recommended

      _rspec_completions() {
        local cur=${COMP_WORDS[COMP_CWORD]}
        local compline="${COMP_WORDS[@]:1:$COMP_CWORD-1}"

        case "$compline" in
          'completion'*'bash')
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --include_aliases" -- "$cur" )
            ;;

          'completion'*'zsh')
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --include_aliases" -- "$cur" )
            ;;

          'completion'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "bash zsh --help --include_aliases" -- "$cur" )
            ;;

          'version'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          'start'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          'echo'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          'stop'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --graceful" -- "$cur" )
            ;;

          'exec'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          *)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "version echo start stop exec completion help" -- "$cur" )
            ;;

        esac
      } &&
      complete -F _rspec_completions rspec

      # ex: filetype=sh
    SCRIPT
  end
end
