# frozen_string_literal: true

require_relative "../../../foo"

RSpec.describe Dry::CLI::Completion::Generator do
  subject do
    Dry::CLI::Completion::Generator.new(Foo::CLI::Commands).call(
      shell: Dry::CLI::Completion::BASH,
      include_aliases: true
    )
  end

  it "returns completion script for bash with aliases" do
    is_expected.to eq <<~SCRIPT
      # rspec completion                                         -*- shell-script -*-

      # This bash completions script was generated by
      # completely (https://github.com/dannyben/completely)
      # Modifying it manually is not recommended

      _rspec_completions() {
        local cur=${COMP_WORDS[COMP_CWORD]}
        local compline="${COMP_WORDS[@]:1:$COMP_CWORD-1}"

        case "$compline" in
          'completion'*'bash')
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --include_aliases -a" -- "$cur" )
            ;;

          'generate config'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --apps" -- "$cur" )
            ;;

          'completion'*'zsh')
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --include_aliases -a" -- "$cur" )
            ;;

          'generate test'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --framework" -- "$cur" )
            ;;

          'completion'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "bash zsh --help --include_aliases -a" -- "$cur" )
            ;;

          '--version'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          'generate'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "config test" -- "$cur" )
            ;;

          'g config'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --apps" -- "$cur" )
            ;;

          'version'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          'g test'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --framework" -- "$cur" )
            ;;

          'start'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          'echo'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          'stop'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --graceful" -- "$cur" )
            ;;

          'exec'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          '-v'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          'v'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
            ;;

          'g'*)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "config test" -- "$cur" )
            ;;

          *)
            while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "version echo start stop exec completion generate v -v --version g help" -- "$cur" )
            ;;

        esac
      } &&
      complete -F _rspec_completions rspec

      # ex: filetype=sh
    SCRIPT
  end
end
