name: Lint, test & build gem

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.6'
          - '3.1.2'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle

    - name: Run linter
      run: bundle exec rubocop

    - name: Run tests
      run: bundle exec rspec

    - name: Build gem
      run: gem build *.gemspec
